#!/usr/bin/with-contenv bash

echo "**** installing Gradle 7.4.2 dev environment ****"

GRADLE_VERSION=7.4

apt-get install -y \
    wget \
    unzip
 
wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip -P /mnt/server/tmp
unzip -d /opt/gradle /mnt/server/tmp/gradle-${GRADLE_VERSION}-bin.zip
ln -s /opt/gradle/gradle-${GRADLE_VERSION} /opt/gradle/latest


export GRADLE_HOME=/opt/gradle/latest
